copy deploy action from Triton module

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,10 +1,24 @@
 # see https://github.com/viamrobotics/build-action for help
 on:
   push:
-    tags:
-      - "[0-9]+.[0-9]+.[0-9]+" # the build-action will trigger on tags with the format 1.0.0
+    release:
+      types: [published]
 
 jobs:
+  validate-tag:  # Make sure the tag we're publishing looks like semantic versioning
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate tag format
+        run: |
+          TAG="${{ github.event.release.tag_name }}"
+          echo "Validating tag: '$TAG'"
+          if [[ $TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]*)?$ ]]; then
+            echo "Tag matches semver."
+          else
+            echo "Error: tag does not match semver."
+            exit 1
+          fi
+
   publish:
     runs-on: ubuntu-latest
     steps:
